version: '3.8'

services:
  doc2html:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=True
      - APP_HOME=/app
      - PORT=5000
    volumes:
      - .:/app